// ─────────────────────────────────────────────────────────────────────────────
// HOMO FABER - קובץ תוכן
// ערוך קובץ זה כדי להוסיף קטגוריות וממצאים.
//
// קטגוריות (CATEGORIES):
//   id    מזהה ייחודי באותיות לטיניות קטנות, ללא רווחים
//   name  שם הקטגוריה כפי שיופיע באתר
//
// ממצאים (ARTIFACTS):
//   id          מזהה ייחודי (אותיות-מקף)
//   name        שם הממצא
//   categoryId  חייב להתאים ל-id של קטגוריה קיימת
//   age         גיל בכתיב חופשי לתצוגה
//   ageNum      שנה כמספר שלם (שלילי = לפנה"ס) - משמש למיון כרונולוגי
//   location    אתר / אזור המוצא
//   material    חומר/ים עיקרי/ים (טקסט חופשי לתצוגה)
//   materials   מערך חומרים לסינון - לדוגמה: ['ברונזה', 'עץ']
//   use         שימוש - חייב להתאים ל-key ב-USE_OPTIONS
//   size        גודל הממצא (טקסט חופשי, לדוגמה: '12 × 8 ס"מ')
//   description פסקת רקע היסטורי
//   media       { type: 'video' | 'image', src: 'media/artifacts/...', poster: '...' }
// ─────────────────────────────────────────────────────────────────────────────

// ── ניתן לערוך: קטגוריות שימוש ──────────────────────────────────────────────
// הוסף, הסר או שנה ערכים לפי הצורך. key = ערך בשדה use של הממצא.
const USE_OPTIONS = [
  { key: 'פולחן',      label: 'פולחן וטקס'    },
  { key: 'קבורה',      label: 'קבורה'          },
  { key: 'חרפושיות',   label: 'חרפושיות'       },
  { key: 'יומיומי',    label: 'יומיום'         },
  { key: 'עיטור',      label: 'עיטור'          },
  { key: 'מסחר',       label: 'מסחר ומינהל'   },
];

const CATEGORIES = [
  {
    id: 'prehistory',
    name: 'פרהסטוריה',
    period: 'עד 233,000 לפנה"ס',
    video: 'media/artifacts/צלמית מבריכת רם.mp4',
    intro: 'האוסף הפרהיסטורי של מוזיאון ישראל מגיע אל ראשית הנוכחות האנושית בארץ ישראל - עד לפני למעלה מ-200,000 שנה. הפריטים מתעדים את המעברים הגדולים בתולדות האדם: מציידים-לקטים נוודים לקהילות חקלאיות מיושבות, ומשימוש בכלי אבן גולמיים לעיבוד חרס, עצם ומתכת ראשונית. הממצאים - כלי צור וחצב, צלמיות חרס ואבן, גולגולות מכויירות, קבורות וחפצי פולחן - מגיעים מאתרים כעינן, גלגל, נחל חמר ונחל עלי, ומשרטטים עולם של אמונות, טקסים וקשרים חברתיים שהתגבשו אלפי שנים לפני המצאת הכתב.',
  },
  {
    id: 'chalcolithic-canaanite',
    name: 'התקופה הכלקוליתית והכנענית',
    period: '4500–1200 לפנה"ס',
    video: 'media/artifacts/כוס נטילת ידיים.mp4',
    flip: true,
    intro: 'האוסף מהתקופה הכלקוליתית והכנענית של מוזיאון ישראל מקיף למעלה מאלפיים שנה של יישוב אנושי בארץ כנען - מהאלף החמישי ועד סוף האלף השני לפני הספירה. זוהי תקופה של ראשיות: ראשית השימוש במתכת, ראשית הכתב, ראשית המסחר בין-אזוריאשית הנוכחות האנושית בארץ ישראל - עד לפני למעלה מ-200,000 שנה. הפריטים מתעדים את המעברים הגדולים בתולדות האדם: מציידים-לקטים נוודים לקהילות חקלאיות מיושבות, ומשימוש בכלי אבן גולמיים לעיבוד חרס, עצם ומתכת ראשונית. הממצאים - כלי צור וחצב, צלמיות חרס ואבן, גולגולות מכויירות, קבורות וחפצי פולחן - מגיעים מאתרים כעינן, גלגל, נחל חמר ונחל עלי, ומשרטטים עולם של אמונות, טקסים וקשרים חברתיים שהתגבשו אלפי שנים לפני המצאת הכתב.',
  },
  {
    id: 'egyptian',
    name: 'ארכיאולוגיה מצרית',
    period: '3100–332 לפנה"ס',
    video: 'media/artifacts/ארון קבורה לחתול.mp4',
    intro: 'האוסף הארכיאולוגי המצרי של מוזיאון ישראל מקיף למעלה מאלפיים שנה של יצירה לאורך עמק הנילוס - מהממלכה הקדומה ועד התקופה הרומית. הפריטים מגלמים את שני הנושאים המרכזיים שסחבה אמנות מצרים העתיקה לאורך כל תולדותיה: המלכות והפולחן. פסלי ברונזה וגרניט של אלים - איזיס, הורוס, בסתת, מאעת - לצד דמויות של פרעונים וכוהנים; ארונות קבורה, תבליטי קיר והיפוסכאות המתארים את המסע אל העולם הבא; חרפושיות ואמולטים שנועדו להגן על נושאיהם בחיים ואחרי המוות. חומרי הגלם - ברונזה, בזלת, אבן גיר, עץ מצוי, פפירוס - שאובים מנוף הנילוס ומעצבים את מראה הפריטים לא פחות מהאמונות שלשמן נוצרו.',
  },
  {
    id: 'classical',
    name: 'ארכיאולוגיה קלאסית',
    period: '800–31 לפנה"ס',
    video: 'media/artifacts/מסיכת דיוניסוס.mp4',
    flip: true,
    intro: 'האוסף הארכיאולוגי הקלאסי של מוזיאון ישראל מציג יצירות מיוון, איטליה ומצרים מהתקופה הארכאית ועד הקלאסית המאוחרת - בין המאה השביעית ועד המאה הרביעית לפני הספירה. לב האוסף הוא כלי החרס האתוניים: כדי יין, כוסות, כדי שמן ואמפורות המצוירים בשיטת הדמויות השחורות והאדומות, ומתארים מיתולוגיה, תחרול אלים - איזיס, הורוס, בסתת, מאעת - לצד דמויות של פרעונים וכוהנים; ארונות קבורה, תבליטי קיר והיפוסכאות המתארים את המסע אל העולם הבא; חרפושיות ואמולטים שנועדו להגן על נושאיהם בחיים ואחרי המוות. חומרי הגלם - ברונזה, בזלת, אבן גיר, עץ מצוי, פפירוס - שאובים מנוף הנילוס ומעצבים את מראה הפריטים לא פחות מהאמונות שלשמן נוצרו.',
  },
  {
    id: 'hellenistic-roman-byzantine',
    name: 'התקופה ההלניסטית, רומית וביזנטית',
    period: '332 לפנה"ס–638 לפנה"ס',
    video: 'media/artifacts/איש נכרי לא ייכנס.mp4',
    intro: 'האוסף מהתקופה ההלניסטית, הרומית והביזנטית של מוזיאון ישראל מקיף כשמונה מאות שנה של חיים באזור הלבנט - מכיבושי אלכסנדר מוקדון במאה הרביעית לפני הספירה ועד שקיעת הממלכה הביזנטית במאה השביעית לספירה. זוהי תקופה של שכבות: תרבות יוונית שחדרה לאדמות המזרח, שלטון רומי שהותיר אחריו ארכיטקטורה, פולחן וכתב, וקהילות יהודיות, נוצריות ואליליות שחיו זו לצד זו ולעיתים זו בתוך זו. הפריטים באוסף משקפים את המגוון הזה: פסלי שיש של אלים רומיים ופסל קיסר, כלי שולחן יומיומיים ועיטורי קבורה, מנורות ורצפות פסיפס, ציורי קיר מכנסיות וגלוסקמאות מחצובות סלע - כל אחד מהם עד לעולם שבו הגבולות בין תרבויות, דתות ושפות היו נזילים ומתמיד משתנים.',
  },
  {
    id: 'islamic',
    name: 'אמנות וארכיאולוגיה אסלאמית',
    period: '638–1917 לפנה"ס',
    video: 'media/artifacts/כד מעוטר בוהק מתכתי.mp4',
    intro: 'האוסף האסלאמי של מוזיאון ישראל מאגד יצירות מתקופות ואזורים גיאוגרפיים מגוונים - מספרד ועד מרכז אסיה, מהמאה השביעית ועד המאה התשע-עשרה. הפריטים מאורגנים לפי תרבות המוצא שלהם: שלטונות ועמים שעיצבו עולמות אמונה וטקס ייחודיים, שאבו חומרי גלם מנופים שונים, ופיתחו טכניקות עיבוד ועיטור משלהם. מהקרמיקה המזוגגת של בגדד העבאסית ועד כלי המתכת של פרס הסלג׳וקית, האוסף מציג כיצד זהות תרבותית באה לידי ביטוי בחומר, בצורה ובמלאכה.',
  },
  {
    id: 'west-asia',
    name: 'תרבויות מערב אסיה',
    period: '3500 לפנה"ס–700 לפנה"ס',
    video: 'media/artifacts/נס מורכב מראשי פרים.mp4',
    intro: 'האוסף הארכיאולוגי ממערב אסיה של מוזיאון ישראל מקיף אלפי שנות יצירה אנושית - מתרבויות מסופוטמוצרו ושימשו באזור הלבנט ובמרחב הים תיכוני הרחב - מהתקופה הפרסית ועד העת החדשה. המטבעות משקפים את רצף השלטונות שעברו על האזור: פרס, יוון, מקדון, רומא, וממלכות יהודיות מקומיות - כל אחד מהם הטביע על המטבע את סמליו, שפתו ודמויותיו. החומר ממנו עשוי המטבע לא היה מקרי: ברונזה ונחושת שימשו לפרוטות היומיום, כסף עמד בבסיס רוב המערכות המוניטריות-  מהדרכמה היוונית ועד שקל ימי המרד-  וזהב שמור היה למטבעות היוקרה של קיסרים ושליטים. ממטבעות השקל של ימי המרד הגדול ומרד בר כוכבא ועד מטבעות נפוליאון ואוקטביאנוס, האוסף מציג כיצד המטבע שימש לא רק אמצעי חליפין אלא כלי פוליטי ותרבותי. הפריטים באוסף משקפים את המגוון הזה: פסלי שיש של אלים רומיים ופסל קיסר, כלי שולחן יומיומיים ועיטורי קבורה, מנורות ורצפות פסיפס, ציורי קיר מכנסיות וגלוסקמאות מחצובות סלע - כל אחד מהם עד לעולם שבו הגבולות בין תרבויות, דתות ושפות היו נזילים ומתמיד משתנים.',
  },
  {
    id: 'numismatics',
    name: 'נומיסמטיקה',
    period: 'מהמאה ה-7 לפנה"ס ואילך',
    video: 'media/artifacts/מטבע קיסר.mp4',
    intro: 'אוסף הנומיסמטיקה של מוזיאון ישראל מתמקד במטבעות שנוצרו ושימשו באזור הלבנט ובמרחב הים תיכוני הרחב - מהתקופה הפרסית ועד העת החדשה. המטבעות משקפים את רצף השלטונות שעברו על האזור: פרס, יוון, מקדון, רומא, וממלכות יהודיות מקומיות - כל אחד מהם הטביע על המטבע את סמליו, שפתו ודמויותיו. החומר ממנו עשוי המטבע לא היה מקרי: ברונזה ונחושת שימשו לפרוטות היומיום, כסף עמד בבסיס רוב המערכות המוניטריות - מהדרכמה היוונית ועד שקל ימי המרד - וזהב שמור היה למטבעות היוקרה של קיסרים ושליטים. ממטבעות השקל של ימי המרד הגדול ומרד בר כוכבא ועד מטבעות נפוליאון ואוקטביאנוס, האוסף מציג כיצד המטבע שימש לא רק אמצעי חליפין אלא כלי פוליטי ותרבותי.',
  },
];

// ── Site intro text ───────────────────────────────────────────────────────────
// Replace the empty string below with your intro paragraph for the home page.
const HOME_INTRO = 'האדם היוצר הוא מיזם אינטראקטיבי מטעם מוזיאון ישראל, שנועד להנגיש את אוסף הארכיאולוגיה המלא של המוזיאון לקהל הרחב. במרכז המיזם עומד עקרון היצירה כגורם מאחד אוניברסלי של האנושות כולה. האוסף סוקר יצירה אנושית בין תרבויות שונות ומגוונות לאורך מעל 300,000 שנה, ומעניק הזדמנות ייחודית להתעמק ולגלות כיצד מלאכה אנושית מייצגת ומאחדת אותנו כחברה אנושית.';

const ARTIFACTS = [
  {
    id: 'artifact-11',
    name: 'צלמית מבריכת רם',
    categoryId: 'prehistory',
    age: 'התקופה הפלאוליתית התחתונה, התרבות האשלית, 233,000 שנה לפני זמננו בקירוב',
    ageNum: -233000,
    location: 'ברכת רם, רמת הגולן',
    material: 'סקוריה',
    materials: ['סקוריה'],
    use: 'פולחן',
    size: 'גובה 3.5 ס"מ, רוחב 2.5 ס"מ, עומק 2.1 ס"מ',
    cardSize: 'size-lg',
    description: '',
    media: { type: 'video', src: 'media/artifacts/צלמית מבריכת רם.mp4' },
  },
  {
    id: 'artifact-13',
    name: 'סמל נחש / דגם מיאנדר',
    categoryId: 'prehistory',
    age: 'התקופה הניאוליתית הקדם-קיראמית א, התרבות הסולטנית, 11,000 שנה לפני זמננו בקירוב',
    ageNum: -9000,
    location: 'נתיב הגדוד',
    material: 'אבן',
    materials: ['אבן'],
    use: 'פולחן',
    size: 'גובה 10.8 ס"מ, רוחב 9 ס"מ, עומק 3.6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/דגם מיאנדר_.png' },
  },
  {
    id: 'artifact-14',
    name: 'מסכה',
    categoryId: 'prehistory',
    age: 'התקופה הנאוליתית הקדם-קרמית ב, האלף ה-7 לפני הספירה',
    ageNum: -6500,
    location: 'מערת נחל חמר',
    material: 'אבן גיר',
    materials: ['אבן גיר', 'אספלט'],
    use: 'פולחן',
    size: 'גובה 26.5 ס"מ, רוחב 15.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/מסכה.png' },
  },
  {
    id: 'artifact-15',
    name: 'נטיפה',
    categoryId: 'prehistory',
    age: 'התקופה הניאוליתית המאוחרת, תרבות ואדי רבה, 7,500 שנה לפני זמננו בקירוב',
    ageNum: -5500,
    location: 'תל עלי',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'עיטור',
    size: 'גובה 9.3 ס"מ, רוחב 8.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/נטיפה_.png' },
  },
  {
    id: 'artifact-16',
    name: 'צלמית אישה (אלת עץ החיים)',
    categoryId: 'prehistory',
    age: 'התקופה הניאוליתית המאוחרת, תרבות ואדי רבה, 7,500 שנה לפני זמננו בקירוב',
    ageNum: -5500,
    location: 'נווה ים',
    material: 'עצם',
    materials: ['עצם'],
    use: 'פולחן',
    size: 'אורך 21.5 ס"מ, רוחב 3.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/צלמית אישה (אלת עץ החיים).png' },
  },
  {
    id: 'artifact-17',
    name: 'צלמית ציפור',
    categoryId: 'prehistory',
    age: 'התקופה הניאוליתית הקדם-קיראמית א, התרבות החיאמית, 11,000 שנה לפני זמננו בקירוב',
    ageNum: -9000,
    location: 'גלגל',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 5.8 ס"מ, רוחב 3.1 ס"מ, עומק 1.8 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/צלמית ציפור_.png' },
  },
  {
    id: 'artifact-18',
    name: 'קבורת אישה עם כלב (יציקה)',
    categoryId: 'prehistory',
    age: 'התקופה האפיפלאוליתית, התרבות הנטופית, 15,000 שנה לפני זמננו בקירוב',
    ageNum: -13000,
    location: 'עינן',
    material: 'יציקה',
    materials: ['יציקה'],
    use: 'קבורה',
    size: 'אורך 115 ס"מ, גובה 16 ס"מ, רוחב 70 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/קבורת אישה עם כלב (יציקה)_.png' },
  },
  {
    id: 'artifact-19',
    name: 'חלוק מחורץ',
    categoryId: 'prehistory',
    age: 'התקופה הנאוליתית הקיראמית, התרבות הירמוכית, 8,000 שנה לפני זמננו בקירוב',
    ageNum: -6000,
    location: 'שער הגולן',
    material: 'בזלת',
    materials: ['בזלת'],
    use: 'פולחן',
    size: 'גובה 8.4 ס"מ, רוחב 6.6 ס"מ, עומק 3.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/חלוק מחורץ.png' },
  },
  {
    id: 'artifact-20',
    name: 'צלמית אלה',
    categoryId: 'prehistory',
    age: 'התקופה הנאוליתית הקיראמית, התרבות הירמוכית, 8,000 שנה לפני זמננו בקירוב',
    ageNum: -6000,
    location: 'שער הגולן',
    material: 'טין',
    materials: ['טין'],
    use: 'פולחן',
    size: 'גובה 15.1 ס"מ, רוחב 6.9 ס"מ, עומק 5.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/צלמית אלה.png' },
  },
  {
    id: 'artifact-21',
    name: 'קערית',
    categoryId: 'prehistory',
    age: 'התקופה הנאוליתית הקיראמית, התרבות הירמוכית, 8,000 שנה לפני זמננו בקירוב',
    ageNum: -6000,
    location: 'חורבת מנחה (מונחתה)',
    material: 'טין',
    materials: ['טין'],
    use: 'יומיומי',
    size: 'גובה 3 ס"מ, קוטר 4.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/קערית.png' },
  },
  {
    id: 'artifact-22',
    name: 'קבורת נער עם קרני יחמור',
    categoryId: 'prehistory',
    age: 'התקופה הפלאוליתית התיכונה, התרבות המוסטרית, 120,000 שנה לפני זמננו בקירוב',
    ageNum: -118000,
    location: 'מערת קפזה',
    material: 'יציקה',
    materials: ['יציקה'],
    use: 'קבורה',
    size: 'אורך 60 ס"מ, רוחב 50 ס"מ, עומק 19 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/קבורת נער עם קרני יחמור_.png' },
  },
  {
    id: 'artifact-23',
    name: 'צלמית ראש אדם',
    categoryId: 'prehistory',
    age: 'התקופה האפיפלאוליתית, התרבות הנטופית, 15,000-13,500 שנה לפני זמננו',
    ageNum: -13000,
    location: 'עינן',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 6.8 ס"מ, רוחב 4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/צלמית ראש אדם.png' },
  },
  {
    id: 'artifact-24',
    name: 'סוס חרות על לוח',
    categoryId: 'prehistory',
    age: 'התקופה הפלאוליתית העליונה, התרבות האוריניאקית, 37,000-32,000 שנה לפני זמננו',
    ageNum: -35000,
    location: 'מערת היונים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 9.6 ס"מ, רוחב 12.5 ס"מ, עובי 2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/סוס חרות על לוח.png' },
  },
  {
    id: 'artifact-25',
    name: 'פסל',
    categoryId: 'prehistory',
    age: 'התקופה הניאוליתית הקדם-קיראמית א, התרבות החיאמית, 11,000 שנה לפני זמננו בקירוב',
    ageNum: -9000,
    location: 'גלגל',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 36 ס"מ, רוחב 17 ס"מ, עומק 9 ס"מ',
    description: '',
    media: null,
  },
  {
    id: 'artifact-26',
    name: 'סמל קשת חרות על לוח',
    categoryId: 'prehistory',
    age: 'התקופה הפלאוליתית התיכונה, התרבות המוסטרית, 55,000 שנים לפני זמננו בקירוב',
    ageNum: -53000,
    location: 'קוניטרה',
    material: 'צור',
    materials: ['צור'],
    use: 'פולחן',
    size: 'גובה 6.7 ס"מ, רוחב 7.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/סמל קשת חרות על לוח.png' },
  },
  {
    id: 'artifact-27',
    name: 'כוס',
    categoryId: 'prehistory',
    age: 'ניאוליתית מאוחרת',
    ageNum: -6000,
    location: 'כברי',
    material: 'אבן',
    materials: ['אבן'],
    use: 'יומיומי',
    size: 'גובה 7 ס"מ, קוטר 6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/כוס_.png' },
  },
  {
    id: 'artifact-28',
    name: 'חרוז',
    categoryId: 'prehistory',
    age: 'ניאוליתית קדם-קיראמית א',
    ageNum: -9000,
    location: 'גלגל',
    material: 'אבן',
    materials: ['אבן'],
    use: 'עיטור',
    size: 'אורך 1 ס"מ, רוחב 0.8 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/חרוז_.png' },
  },
  {
    id: 'artifact-29',
    name: 'כלי צור מוכתם באוכרה',
    categoryId: 'prehistory',
    age: 'פליאולית עליון',
    ageNum: -30000,
    location: 'לא ידוע',
    material: 'צור',
    materials: ['צור'],
    use: 'יומיומי',
    size: 'אורך 7.7 ס"מ, רוחב 2.5 ס"מ, עובי 0.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/כלי צור מוכתם באוכרה.png' },
  },
  {
    id: 'artifact-30',
    name: 'חלוק מחורץ',
    categoryId: 'prehistory',
    age: 'ניאוליתית קדם-קיראמית א',
    ageNum: -9000,
    location: 'גלגל',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'אורך 9.5 ס"מ, רוחב 5.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/חלוק מחורץ גלגל.png' },
  },
  {
    id: 'artifact-31',
    name: 'קדרה',
    categoryId: 'prehistory',
    age: 'ניאוליתית קיראמית',
    ageNum: -6000,
    location: 'חורבת מנחה (מונחתה)',
    material: 'טין',
    materials: ['טין'],
    use: 'יומיומי',
    size: 'גובה 23 ס"מ, קוטר 25 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/קדרה.png' },
  },
  {
    id: 'artifact-32',
    name: 'ראש חץ',
    categoryId: 'prehistory',
    age: 'ניאוליתית קיראמית',
    ageNum: -6000,
    location: 'אתר לא ידוע',
    material: 'צור',
    materials: ['צור'],
    use: 'יומיומי',
    size: 'אורך 2.7 ס"מ, רוחב 1.3 ס"מ, עובי 0.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/ראש חץ.png' },
  },
  {
    id: 'artifact-33',
    name: 'עלי',
    categoryId: 'prehistory',
    age: 'התקופה האפיפלאוליתית, התרבות החריפאית, 13,000-11,000 שנה לפני זמננו',
    ageNum: -10000,
    location: 'אבו סאלם (G12)',
    material: 'בזלת',
    materials: ['בזלת'],
    use: 'יומיומי',
    size: 'גובה 8.4 ס"מ, רוחב 10.8 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/עלי_.png' },
  },
  {
    id: 'artifact-34',
    name: 'קערה',
    categoryId: 'prehistory',
    age: 'ניאוליתית קיראמית',
    ageNum: -6000,
    location: 'חורבת מנחה (מונחתה)',
    material: 'טין',
    materials: ['טין'],
    use: 'יומיומי',
    size: 'גובה 10 ס"מ, קוטר 17.8 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/קערה.png' },
  },
  {
    id: 'artifact-35',
    name: 'נטיפה',
    categoryId: 'prehistory',
    age: 'פליאולית עליון',
    ageNum: -30000,
    location: 'מערת היונים',
    material: 'שן',
    materials: ['שן'],
    use: 'עיטור',
    size: 'אורך 2.5 ס"מ, רוחב 1.1 ס"מ, עובי 0.6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/נטיפה.png' },
  },
  {
    id: 'artifact-36',
    name: 'קנקנית',
    categoryId: 'prehistory',
    age: 'התקופה הנאוליתית הקיראמית, התרבות הירמוכית, 8,000 שנה לפני זמננו בקירוב',
    ageNum: -6000,
    location: 'חורבת מנחה (מונחתה)',
    material: 'טין',
    materials: ['טין'],
    use: 'יומיומי',
    size: 'גובה 10 ס"מ, קוטר 7.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/קנקנית.png' },
  },
  {
    id: 'artifact-37',
    name: 'דמות בעל חיים על ידית מגל',
    categoryId: 'prehistory',
    age: 'התקופה האפיפלאוליתית, התרבות הנטופית, 15,000-13,500 שנה לפני זמננו',
    ageNum: -13000,
    location: 'מערת אל ואד',
    material: 'עצם',
    materials: ['עצם'],
    use: 'יומיומי',
    size: 'גובה 10.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/דמות בעל חיים על ידית מגל.png' },
  },
  {
    id: 'artifact-38',
    name: 'ראש חץ',
    categoryId: 'prehistory',
    age: 'ניאוליתית קדם-קיראמית ב',
    ageNum: -7000,
    location: 'אתר לא ידוע',
    material: 'צור',
    materials: ['צור'],
    use: 'יומיומי',
    size: 'אורך 6.3 ס"מ, רוחב 1.4 ס"מ, עובי 0.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/ראש חץ 2.png' },
  },
  {
    id: 'artifact-39',
    name: 'שבר פסל',
    categoryId: 'prehistory',
    age: 'ניאוליתית קדם-קיראמית ב',
    ageNum: -7000,
    location: 'מערת נחל חמר',
    material: 'טיח',
    materials: ['טיח'],
    use: 'פולחן',
    size: 'אורך 10.5 ס"מ, רוחב 6.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/שבר פסל.png' },
  },
  {
    id: 'artifact-40',
    name: 'ראש חץ',
    categoryId: 'prehistory',
    age: 'ניאוליתית קדם-קיראמית א',
    ageNum: -9000,
    location: 'גלגל',
    material: 'צור',
    materials: ['צור'],
    use: 'יומיומי',
    size: 'אורך 2.7 ס"מ, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/ראש חץ 3.png' },
  },
  {
    id: 'artifact-41',
    name: 'צלמית ראש אדם',
    categoryId: 'prehistory',
    age: 'התקופה האפיפלאוליתית, התרבות הנטופית, 15,000-13,500 שנה לפני זמננו',
    ageNum: -13000,
    location: 'עינן',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'אורך 8 ס"מ, רוחב 6.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/צלמית ראש אדם 2.png' },
  },
  {
    id: 'artifact-42',
    name: 'צלמית בעל חיים',
    categoryId: 'prehistory',
    age: 'התקופה האפיפלאוליתית, התרבות הנטופית, 15,000 שנה לפני זמננו בקירוב',
    ageNum: -13000,
    location: 'נחל אורן',
    material: 'עצם',
    materials: ['עצם'],
    use: 'פולחן',
    size: 'גובה 4.1 ס"מ, עומק 2.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/prehistoric/צלמית בעל חיים.png' },
  },
  {
    id: 'artifact-06',
    name: 'כוס נטילת ידיים',
    categoryId: 'chalcolithic-canaanite',
    age: '',
    ageNum: -3500,
    location: '',
    material: 'חרס',
    materials: ['חרס'],
    use: 'פולחן',
    description: '',
    media: { type: 'video', src: 'media/artifacts/כוס נטילת ידיים.mp4', flip: true },
  },
  {
    id: 'artifact-07',
    name: 'מטה תקופה כנענית',
    categoryId: 'chalcolithic-canaanite',
    age: '',
    ageNum: -2000,
    location: '',
    material: 'נחושת',
    materials: ['נחושת'],
    use: 'פולחן',
    description: '',
    media: { type: 'video', src: 'media/artifacts/מטה תקופה כנענית.mp4' },
  },
  {
    id: 'artifact-09',
    name: 'ארון קבורה לחתול',
    categoryId: 'egyptian',
    age: 'המאה ה-4 לפני הספירה',
    ageNum: -400,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'קבורה',
    size: 'גובה 47.2 ס"מ, רוחב 21 ס"מ',
    description: '',
    glyph: '𓎯𓏏𓏏𓁐',
    note: 'טקס חניטה וקבורה של חתול במצרים העתיקה\n\nבמצרים העתיקה נחשב החתול לבעל חיים קדוש, ומותו עורר אבל במשפחה. הכוהנים ניקו את גוף החתול והשרו אותו במלח מיוחד לייבוש, ולאחר מכן עטפו אותו ברצועות פשתן בקפידה, לעיתים עם מסכה המזכירה את פניו. הגופה החנוטה הונחה בארון קטן בצורת חתול, לעיתים בצירוף קורבנות מאכל כמו חלב או עכברים חנוטים. לבסוף נקבר החתול בבית קברות מיוחד לבעלי חיים, במעמד שביטא את הקדושה שיוחסה לו.',
    media: { type: 'video', src: 'media/artifacts/ארון קבורה לחתול.mp4' },
  },
  {
    id: 'artifact-12',
    name: 'מסיכת דיוניסוס',
    categoryId: 'classical',
    age: '',
    ageNum: -400,
    location: '',
    material: 'חרס',
    materials: ['חרס'],
    use: 'פולחן',
    description: '',
    media: { type: 'video', src: 'media/artifacts/מסיכת דיוניסוס.mp4', flip: true },
  },
  {
    id: 'artifact-03',
    name: 'פך בסגנון מינאי',
    categoryId: 'hellenistic-roman-byzantine',
    age: '',
    ageNum: -100,
    location: '',
    material: 'זכוכית',
    materials: ['זכוכית'],
    use: 'יומיומי',
    description: '',
    media: { type: 'video', src: 'media/artifacts/פך בסגנון מינאי.mp4', flip: true },
  },
  {
    id: 'artifact-04',
    name: 'איש נכרי לא ייכנס',
    categoryId: 'hellenistic-roman-byzantine',
    age: '',
    ageNum: -30,
    location: '',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    description: '',
    media: { type: 'video', src: 'media/artifacts/איש נכרי לא ייכנס.mp4' },
  },
  {
    id: 'artifact-01',
    name: 'כד מעוטר בוהק מתכתי',
    categoryId: 'islamic',
    age: '',
    ageNum: 1200,
    location: '',
    material: 'חרס מזוגג',
    materials: ['חרס מזוגג'],
    use: 'יומיומי',
    description: '',
    media: { type: 'video', src: 'media/artifacts/כד מעוטר בוהק מתכתי.mp4' },
  },
  {
    id: 'artifact-02',
    name: 'נס מורכב מראשי פרים',
    categoryId: 'west-asia',
    age: '',
    ageNum: -2500,
    location: '',
    material: 'נחושת',
    materials: ['נחושת'],
    use: 'פולחן',
    description: '',
    media: { type: 'video', src: 'media/artifacts/נס מורכב מראשי פרים.mp4' },
  },
  {
    id: 'artifact-05',
    name: 'פסל גלגל',
    categoryId: 'west-asia',
    age: '',
    ageNum: -3000,
    location: '',
    material: 'אבן',
    materials: ['אבן'],
    use: 'פולחן',
    description: '',
    media: { type: 'video', src: 'media/artifacts/פסל גלגל.mp4' },
  },
  {
    id: 'artifact-08',
    name: 'מטבע קיסר',
    categoryId: 'numismatics',
    age: '',
    ageNum: -50,
    location: '',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'מסחר',
    description: '',
    media: { type: 'video', src: 'media/artifacts/מטבע קיסר.mp4' },
  },
  {
    id: 'artifact-10',
    name: 'קנקן',
    categoryId: 'chalcolithic-canaanite',
    age: '',
    ageNum: -4000,
    location: '',
    material: 'חרס',
    materials: ['חרס'],
    use: 'יומיומי',
    description: '',
    media: { type: 'video', src: 'media/artifacts/קנקן.mp4' },
  },

  // ── ארכיאולוגיה מצרית ─────────────────────────────────────────────────────
  {
    id: 'eg-02',
    name: 'שפופרת כחל',
    categoryId: 'egyptian',
    age: 'מאה 14 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'שנהב',
    materials: ['שנהב'],
    use: 'עיטור',
    size: 'גובה 10 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שפופרת כחל.png' },
  },
  {
    id: 'eg-03',
    name: 'ראש מלך ו״אוריאוס״',
    categoryId: 'egyptian',
    age: 'מאה 14 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 17 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/ראש מלך.png' },
  },
  {
    id: 'eg-04',
    name: 'אסטלת קבורה של חוֹר',
    categoryId: 'egyptian',
    age: 'מאה 7–6 לפנה"ס',
    ageNum: -650,
    location: 'מצרים',
    material: 'עץ',
    materials: ['עץ'],
    use: 'קבורה',
    size: 'גובה 32 ס"מ, רוחב 22 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/אסטלת קבורה.png' },
  },
  {
    id: 'eg-05',
    name: 'צלמית מאעת',
    categoryId: 'egyptian',
    age: 'תקופת הביניים השלישית, המאה ה-8 עד ה-7 לפני הספירה',
    ageNum: -750,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 7.4 ס"מ, רוחב 2 ס"מ',
    description: 'צלמית מאעת יושבת ולראשה נוצת יען, סימן ההיכר שלה',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית מאעת.png' },
  },
  {
    id: 'eg-06',
    name: 'צלמית נושאת מנחה',
    categoryId: 'egyptian',
    age: 'המאה ה-21 עד ה-20 לפני הספירה',
    ageNum: -2050,
    location: 'המוצא אינו ידוע',
    material: 'עץ',
    materials: ['עץ'],
    use: 'פולחן',
    size: 'גובה 59 ס"מ',
    description: 'צלמית של נושאת מנחה שעל ראשה קופסת קמח ובידה ברווז',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית של נושאת.png' },
  },
  {
    id: 'eg-07',
    name: 'צלמית שבתי',
    categoryId: 'egyptian',
    age: 'המאה ה-13 לפני הספירה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'קבורה',
    size: 'גובה 24.7 ס"מ, רוחב 9 ס"מ',
    description: 'צלמית שבתי מהודרת של "גבירת הבית", תואר המכוון לאישה נשואה',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית שבתי.png' },
  },
  {
    id: 'eg-08',
    name: 'צלמית פתח',
    categoryId: 'egyptian',
    age: 'המאה ה-8 עד ה-7 לפני הספירה',
    ageNum: -750,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 15.5 ס"מ, רוחב 5 ס"מ',
    description: 'צלמית של פתח, אל עיר הבירה ממפיס ופטרון האומנים',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית של פתח.png' },
  },
  {
    id: 'eg-09',
    name: 'חרפושית-לב',
    categoryId: 'egyptian',
    age: 'המאה ה-15 לפני הספירה',
    ageNum: -1450,
    location: 'מצרים',
    material: 'פיליט',
    materials: ['פיליט'],
    use: 'חרפושיות',
    size: 'גובה 6.6 ס"מ, רוחב 5.3 ס"מ',
    description: 'חרפושית-לב ועליה הלחש הקבוע, שבו נדרש הלב שלא להעיד נגד בעליו בעת טקס שקילתו',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית-לב.png' },
  },
  {
    id: 'eg-10',
    name: 'משחק סנת',
    categoryId: 'egyptian',
    age: 'הממלכה החדשה, השושלת ה-18 עד ה-19',
    ageNum: -1300,
    location: 'אזור טניס, מצרים',
    material: 'תרכיב מזוגג',
    materials: ['תרכיב מזוגג'],
    use: 'יומיומי',
    size: 'גובה 3.3 ס"מ, אורך 33.5 ס"מ',
    description: 'משחק סנת, כולל לוח ועשרים אבני משחק',
    media: { type: 'image', src: 'media/artifacts/egyptian/משחק סנת.png' },
  },
  {
    id: 'eg-11',
    name: 'צלמית איזיס',
    categoryId: 'egyptian',
    age: 'המאה ה-5 עד ה-3 לפני הספירה',
    ageNum: -400,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 15 ס"מ, רוחב 6.5 ס"מ',
    description: 'צלמית בדמות איזיס, האם המגוננת על בנה הורוס הילד',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית בדמות איזיס.png' },
  },
  {
    id: 'eg-12',
    name: 'שבר תבליט - סוסים ומרכבה',
    categoryId: 'egyptian',
    age: 'מאה 14 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 21, רוחב 32 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שבר תבליט המתאר צמד.png' },
  },
  {
    id: 'eg-13',
    name: 'קטעי תכריך - דיוקן אישה',
    categoryId: 'egyptian',
    age: 'המאה ה-4 לספירה',
    ageNum: 350,
    location: 'מצרים',
    material: 'פשתן',
    materials: ['פשתן'],
    use: 'קבורה',
    size: 'גובה 66 ס"מ, רוחב 29 ס"מ',
    description: 'קטעי תכריך ועליו דיוקן אישה עדויה תכשיטים',
    media: { type: 'image', src: 'media/artifacts/egyptian/קטעי תכריך.png' },
  },
  {
    id: 'eg-14',
    name: 'צלמית הורוס הילד',
    categoryId: 'egyptian',
    age: 'המאה ה-3 עד ה-2 לפני הספירה',
    ageNum: -250,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 14 ס"מ, רוחב 4.5 ס"מ',
    description: 'צלמית הורוס הילד, מוצג עירום, אצבעו נתונה בפיו ותלתל הילדות צונח לצד ראשו',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית הורוס הילד.png' },
  },
  {
    id: 'eg-15',
    name: 'ציור קבר - שני כוהנים',
    categoryId: 'egyptian',
    age: 'המאה ה-14 לפני הספירה',
    ageNum: -1350,
    location: 'תביי, מצרים',
    material: 'גבס',
    materials: ['גבס'],
    use: 'קבורה',
    size: 'גובה 15.6 ס"מ',
    description: 'ציור קבר המתאר שני כוהנים, האחד אוחז מגילת פפירוס והשני כד נסך',
    media: { type: 'image', src: 'media/artifacts/egyptian/ציור קבר המתאר.png' },
  },
  {
    id: 'eg-16',
    name: 'תבליט קבר - הנפטר',
    categoryId: 'egyptian',
    age: 'הממלכה הקדומה, סוף השושלת ה-6, המאה ה-24 עד ה-22 לפני הספירה',
    ageNum: -2300,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'קבורה',
    size: 'גובה 63 ס"מ',
    description: 'תבליט קבר המתאר את הנפטר מחזיק בידו שרביט המאפיין נושאי משרה רמה',
    media: { type: 'image', src: 'media/artifacts/egyptian/תבליט קבר המתאר את הנפטר.png' },
  },
  {
    id: 'eg-18',
    name: 'פסל קובייה של כוהן לסוֹפֶּד',
    categoryId: 'egyptian',
    age: 'המאה ה-7 לפני הספירה',
    ageNum: -650,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 29 ס"מ, רוחב 14 ס"מ',
    description: 'פסל קובייה של כוהן לסופד, אל הספר המזרחי של מצרים',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסל קובייה של כהן.png' },
  },
  {
    id: 'eg-19',
    name: 'לוחית מנחה',
    categoryId: 'egyptian',
    age: 'התקופה המאוחרת עד התקופה התלמית, המאה ה-5 עד ה-1 לפני הספירה',
    ageNum: -300,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 9 ס"מ, רוחב 13 ס"מ',
    description: 'לוחית מנחה ועליה התואר "זה של שתי הגבירות", המבטא את שלטון המלך על שתי הארצות',
    media: { type: 'image', src: 'media/artifacts/egyptian/לוחית מנחה.png' },
  },
  {
    id: 'eg-20',
    name: 'קטע תבליט - מנחות לאתן',
    categoryId: 'egyptian',
    age: 'המאה ה-14 לפני הספירה',
    ageNum: -1350,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 23 ס"מ, רוחב 28 ס"מ',
    description: 'קטע מתבליט המתאר את המלך מגיש יין לאתן; שם האל נתון בכרטושים כמקובל באמנות עמארנה',
    media: { type: 'image', src: 'media/artifacts/egyptian/קטע תבליט המתאר את פנים.png' },
  },
  {
    id: 'eg-21',
    name: 'צלמית אימני',
    categoryId: 'egyptian',
    age: 'הממלכה התיכונה, השושלת ה-12, המאה ה-20 לפני הספירה',
    ageNum: -2000,
    location: 'מצרים',
    material: 'שחם',
    materials: ['שחם'],
    use: 'פולחן',
    size: 'גובה 29.3 ס"מ, רוחב 14.2 ס"מ',
    description: 'צלמית בדמותו של אימני, הממונה על הזמרים, יושב בתנוחת סופרים ויד שמאלו על חזהו במחוות הערצה לאלים',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית בדמותו של אימני.png' },
  },
  {
    id: 'eg-22',
    name: 'צלמית בז',
    categoryId: 'egyptian',
    age: 'המאה ה-7 עד ה-6 לפני הספירה',
    ageNum: -650,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 21 ס"מ',
    description: 'צלמית בדמות בז, התגלמות הורוס המלך האלוהי בדמות בעל חיים',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית בדמות בז.png' },
  },
  {
    id: 'eg-23',
    name: 'צדפת קונכייה - שנוסרת',
    categoryId: 'egyptian',
    age: 'המאה ה-20 לפני הספירה',
    ageNum: -2000,
    location: 'מצרים',
    material: 'זהב',
    materials: ['זהב'],
    use: 'פולחן',
    size: 'גובה 10 ס"מ, רוחב 10 ס"מ',
    description: 'צדפת קונכייה ועליה שם הלידה של המלך שנוסרת הראשון',
    media: { type: 'image', src: 'media/artifacts/egyptian/צדפת קונכייה.png' },
  },
  {
    id: 'eg-24',
    name: 'חרפושית - אמנחתפ הג׳ ותיי',
    categoryId: 'egyptian',
    age: 'מאה 14 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'אורך 4.4, רוחב 3.1, עומק 2.1 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית הנושאת את של המלך.png' },
  },
  {
    id: 'eg-25',
    name: 'חרפושית - תחותמס השלישי',
    categoryId: 'egyptian',
    age: 'שושלת 18',
    ageNum: -1450,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'גובה 0.7, אורך 1.6, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית הנושאת_.png' },
  },
  {
    id: 'eg-26',
    name: 'חרפושית - אמנחותפ הראשון',
    categoryId: 'egyptian',
    age: 'שושלת 18',
    ageNum: -1500,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'אורך 1.4, רוחב 1 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית ועלייה שם המלכות_.png' },
  },
  {
    id: 'eg-27',
    name: 'חרפושית - ברכה לפתח',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'בדולח הרים',
    materials: ['בדולח הרים'],
    use: 'חרפושיות',
    size: 'אורך 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית ועליה ברכה.png' },
  },
  {
    id: 'eg-28',
    name: 'חרפושית כנענית',
    categoryId: 'egyptian',
    age: 'ברונזה תיכונה',
    ageNum: -1700,
    location: 'לא ידוע',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'אורך 1.6, רוחב 1.1 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית כנענית.png' },
  },
  {
    id: 'eg-29',
    name: 'חרפושית - משלבת סלילים ונפר',
    categoryId: 'egyptian',
    age: 'ממלכה תיכונה מאוחרת',
    ageNum: -1750,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'גובה 0.8, אורך 1.7, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית מעוטרת.png' },
  },
  {
    id: 'eg-30',
    name: 'שבר תבליט - ראש המלך',
    categoryId: 'egyptian',
    age: 'מאה 14 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'אבן חול',
    materials: ['אבן חול'],
    use: 'פולחן',
    size: 'גובה 18, רוחב 14.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שבר תבליט של ראש המלך.png' },
  },
  {
    id: 'eg-31',
    name: 'פסלון האל תוּתוּ',
    categoryId: 'egyptian',
    age: 'תלמית, מאה 3–2 לפנה"ס',
    ageNum: -250,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'אורך 14.8, רוחב 9.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון בדמות האל תותו.png' },
  },
  {
    id: 'eg-32',
    name: 'קמיע - סח׳מת',
    categoryId: 'egyptian',
    age: 'מאה 7–5 לפנה"ס',
    ageNum: -600,
    location: 'מצרים',
    material: 'זהב',
    materials: ['זהב'],
    use: 'פולחן',
    size: 'גובה 2.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קמיע בדמות סחמת.png' },
  },
  {
    id: 'eg-33',
    name: 'קערת תמרוקים - קוף',
    categoryId: 'egyptian',
    age: 'מאה 20–19 לפנה"ס',
    ageNum: -1950,
    location: 'מצרים',
    material: 'אנהידריט',
    materials: ['אנהידריט'],
    use: 'קבורה',
    size: 'גובה 3.5, רוחב 7.6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קערת תמרוקים.png' },
  },
  {
    id: 'eg-34',
    name: 'קטע תבליט - מלך מגיש יין לאתן',
    categoryId: 'egyptian',
    age: 'מאה 14 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 23, רוחב 28 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קטע תבליט המתאר את המלך מגיש.png' },
  },
  {
    id: 'eg-35',
    name: 'קמע - אנוביס',
    categoryId: 'egyptian',
    age: 'מאה 7–5 לפנה"ס',
    ageNum: -600,
    location: 'מצרים',
    material: 'לאפיס לזולי',
    materials: ['לאפיס לזולי'],
    use: 'פולחן',
    size: 'אורך 2.2, רוחב 2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קמע בדמות האל אנוביס.png' },
  },
  {
    id: 'eg-36',
    name: 'חרפושית - ספינקס כורע',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'אורך 1.4, רוחב 0.9 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית ועליה המלך בדמות ספינקס.png' },
  },
  {
    id: 'eg-37',
    name: 'חרפושית - נוסחת ברכה',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת',
    ageNum: -500,
    location: 'מצרים',
    material: 'אגאט',
    materials: ['אגאט'],
    use: 'חרפושיות',
    size: 'אורך 2, רוחב 1.6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית ועליה נוסחת ברכה.png' },
  },
  {
    id: 'eg-38',
    name: 'חרפושית - ללא עיטור (אחלמה)',
    categoryId: 'egyptian',
    age: 'ממלכה תיכונה',
    ageNum: -1850,
    location: 'מצרים',
    material: 'אחלמה',
    materials: ['אחלמה'],
    use: 'חרפושיות',
    size: 'אורך 1.1, רוחב 0.7 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית בלא עיטור או סימן.png' },
  },
  {
    id: 'eg-39',
    name: 'קמע דמוי-פני אדם - ספינקס ומאעת',
    categoryId: 'egyptian',
    age: 'תקופה רעמססית',
    ageNum: -1200,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 0.8, אורך 1.8, רוחב 1.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קמע דמוי-פנים.png' },
  },
  {
    id: 'eg-40',
    name: 'חרפושית מכונפת',
    categoryId: 'egyptian',
    age: 'תלמית מוקדמת',
    ageNum: -300,
    location: 'מצרים',
    material: 'תרכיב מזוגג',
    materials: ['תרכיב מזוגג'],
    use: 'חרפושיות',
    size: 'גובה 9.4, רוחב 12.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית מכונפת.png' },
  },
  {
    id: 'eg-41',
    name: 'חרפושית - קווים צולבים',
    categoryId: 'egyptian',
    age: 'שושלת 18–19',
    ageNum: -1300,
    location: 'מצרים',
    material: 'קרניאול',
    materials: ['קרניאול'],
    use: 'חרפושיות',
    size: 'אורך 1.2, רוחב 0.8 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית מעוטרת בדגם קווים.png' },
  },
  {
    id: 'eg-42',
    name: 'שבר פסל קובייה',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת, מאה 7–4 לפנה"ס',
    ageNum: -550,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 35, רוחב 22 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שבר של פסל קובייה.png' },
  },
  {
    id: 'eg-43',
    name: 'אסטלת קיפוס - הורוס',
    categoryId: 'egyptian',
    age: 'תלמית, מאה 3–2 לפנה"ס',
    ageNum: -250,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 9.6, רוחב 4.9 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/אסטלת קיפוס.png' },
  },
  {
    id: 'eg-44',
    name: 'מכסה ארון לקבורת בז',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת, מאה 7–5 לפנה"ס',
    ageNum: -600,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'קבורה',
    size: 'גובה 16, רוחב 15.3, עומק 4.9 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/מכסה לארון לקבורת בז.png' },
  },
  {
    id: 'eg-45',
    name: 'פסלון קבורה של פקיד',
    categoryId: 'egyptian',
    age: 'ממלכה קדומה, שושלת 6',
    ageNum: -2300,
    location: 'מצרים',
    material: 'עץ',
    materials: ['עץ'],
    use: 'קבורה',
    size: 'גובה 19.5, רוחב 5.6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון קבורה של פקיד רב דרג.png' },
  },
  {
    id: 'eg-46',
    name: 'חרפושית מרובת-יחידות',
    categoryId: 'egyptian',
    age: 'תקופת ביניים שנייה',
    ageNum: -1600,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'חרפושיות',
    size: 'גובה 0.4, אורך 1.3, רוחב 0.7 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית מורבת.png' },
  },
  {
    id: 'eg-47',
    name: 'קמע - עקרב',
    categoryId: 'egyptian',
    age: 'שושלת 18',
    ageNum: -1400,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 0.5, אורך 1.5, רוחב 1.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קמע מעוגל.png' },
  },
  {
    id: 'eg-48',
    name: 'שבר תבליט - אישה עם לוטוס',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה, מאה 16–11 לפנה"ס',
    ageNum: -1300,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'קבורה',
    size: 'גובה 11, רוחב 10 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שבר תבליט שמתוארת בו.png' },
  },
  {
    id: 'eg-49',
    name: 'תיבת מזון - ברווז',
    categoryId: 'egyptian',
    age: 'מאה 20–19 לפנה"ס',
    ageNum: -1950,
    location: 'מצרים',
    material: 'בהט',
    materials: ['בהט'],
    use: 'קבורה',
    size: 'גובה 31.5, רוחב 16 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/תיבת מזון.png' },
  },
  {
    id: 'eg-50',
    name: 'שיבוץ - ראש גבר',
    categoryId: 'egyptian',
    age: 'שושלת 18, 1500–1200 לפנה"ס',
    ageNum: -1350,
    location: 'מצרים',
    material: 'ישפה',
    materials: ['ישפה'],
    use: 'עיטור',
    size: 'גובה 4.5 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שיבוץ בדמות ראש גבר.png' },
  },
  {
    id: 'eg-51',
    name: 'פסלון אפּיס',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת, מאה 7–5 לפנה"ס',
    ageNum: -600,
    location: 'מצרים',
    material: 'בזלת',
    materials: ['בזלת'],
    use: 'פולחן',
    size: 'גובה 10.1, רוחב 2.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון אפיס בדמות אדם.png' },
  },
  {
    id: 'eg-52',
    name: 'חרפושית - ללא עיטור (בדולח הרים)',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'בדולח הרים',
    materials: ['בדולח הרים'],
    use: 'חרפושיות',
    size: 'אורך 1.8, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית בלא עיטור וסימן.png' },
  },
  {
    id: 'eg-53',
    name: 'פסלון דג אוּכּסירינכוּס',
    categoryId: 'egyptian',
    age: 'תלמית, מאה 3–2 לפנה"ס',
    ageNum: -250,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 5.8, אורך 9.1 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון של דג.png' },
  },
  {
    id: 'eg-54',
    name: 'קמע - קנקן בירה',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה, מאה 15–11 לפנה"ס',
    ageNum: -1300,
    location: 'מצרים',
    material: 'תרכיב מזוגג',
    materials: ['תרכיב מזוגג'],
    use: 'פולחן',
    size: 'גובה 4.3, רוחב 2.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קמע דמוי קנקן בירה.png' },
  },
  {
    id: 'eg-55',
    name: 'מכסה כד קנופי',
    categoryId: 'egyptian',
    age: 'סוף ממלכה חדשה',
    ageNum: -1100,
    location: 'מצרים',
    material: 'עץ',
    materials: ['עץ'],
    use: 'קבורה',
    size: 'גובה 13.5, רוחב 14.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/מכסה של כד קנופי.png' },
  },
  {
    id: 'eg-56',
    name: 'צלמית בבון - תחות',
    categoryId: 'egyptian',
    age: 'תלמית, מאה 3–2 לפנה"ס',
    ageNum: -250,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 11, רוחב 4.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית בדמות בבון.png' },
  },
  {
    id: 'eg-57',
    name: 'פסלון היפופוטם',
    categoryId: 'egyptian',
    age: 'שושלת 12, מאה 20–19 לפנה"ס',
    ageNum: -1950,
    location: 'מצרים',
    material: 'תרכיב מזוגג',
    materials: ['תרכיב מזוגג'],
    use: 'פולחן',
    size: 'אורך 8.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון של היפופוטם.png' },
  },
  {
    id: 'eg-58',
    name: 'צלמית דז׳ד-דז׳חותי-יופ-ענח׳',
    categoryId: 'egyptian',
    age: 'מאה 6 לפנה"ס',
    ageNum: -550,
    location: 'מצרים',
    material: 'שחם',
    materials: ['שחם'],
    use: 'פולחן',
    size: 'גובה 19, רוחב 6 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית בדמותו של דז׳ד.png' },
  },
  {
    id: 'eg-59',
    name: 'רביד וֵסֶח׳',
    categoryId: 'egyptian',
    age: 'תלמית, מאה 3–1 לפנה"ס',
    ageNum: -200,
    location: 'מצרים',
    material: 'קרטונאז׳',
    materials: ['קרטונאז׳'],
    use: 'קבורה',
    size: 'גובה 21.5, רוחב 37 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/רביד וסח.png' },
  },
  {
    id: 'eg-60',
    name: 'שבר תבליט - קברו של הממונה על כוהני סוֹפֶּד',
    categoryId: 'egyptian',
    age: 'שושלת 26, מאה 6–4 לפנה"ס',
    ageNum: -500,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'קבורה',
    size: 'גובה 72, רוחב 37 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שבר של תבליט מקברו של.png' },
  },
  {
    id: 'eg-61',
    name: 'חרפושית - בז לצד כינוי',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'ישפה',
    materials: ['ישפה'],
    use: 'חרפושיות',
    size: 'אורך 1.4, רוחב 0.9 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית ועליה דמות בז.png' },
  },
  {
    id: 'eg-62',
    name: 'סיטוּלָה - כלי נסך',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת–תלמית, מאה 7–1 לפנה"ס',
    ageNum: -400,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 13.7, רוחב 4.9 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/סיטולה, כלי נסך.png' },
  },
  {
    id: 'eg-63',
    name: 'שבר ראש פּתָח',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'בזלת',
    materials: ['בזלת'],
    use: 'פולחן',
    size: 'גובה 27, רוחב 21 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/שבר של ראש פתח.png' },
  },
  {
    id: 'eg-64',
    name: 'פסלון הורוס הבז',
    categoryId: 'egyptian',
    age: 'סוף תלמית–רומית',
    ageNum: -100,
    location: 'מצרים',
    material: 'אבן גיר',
    materials: ['אבן גיר'],
    use: 'פולחן',
    size: 'גובה 20.3, רוחב 5.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון בדמות הורוס הבז.png' },
  },
  {
    id: 'eg-65',
    name: 'קמע-חותם - קוף',
    categoryId: 'egyptian',
    age: 'תקופת ביניים ראשונה',
    ageNum: -2100,
    location: 'מצרים',
    material: 'עצם',
    materials: ['עצם'],
    use: 'פולחן',
    size: 'גובה 0.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קָמֵעַ-חותם דמוי-כפתור שבסיסו מעוטר בקוף.png' },
  },
  {
    id: 'eg-67',
    name: 'לוחית מלבנית - דג ואמנחותפ',
    categoryId: 'egyptian',
    age: 'שושלת 18',
    ageNum: -1400,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 0.6, אורך 1.6, רוחב 1.3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/לוחית מלבנית שעל צִדה האחד דמות דג.png' },
  },
  {
    id: 'eg-68',
    name: 'פסלון עיט מסוכך על בז',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת, מאה 7–5 לפנה"ס',
    ageNum: -600,
    location: 'מצרים',
    material: 'תרכיב מזוגג',
    materials: ['תרכיב מזוגג'],
    use: 'פולחן',
    size: 'גובה 4.2, אורך 6.8, רוחב 3 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון של עיט מסוכך על בז.png' },
  },
  {
    id: 'eg-69',
    name: 'קמע - שתי דמויות גברים',
    categoryId: 'egyptian',
    age: 'תקופת ביניים ראשונה',
    ageNum: -2100,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 1.9, אורך 1.4, רוחב 1.4 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קָמֵעַ שבגבו שתי דמויות גברים יושבים גב אל גב ובסיסו מעוטר בדגם סכֵמטי_.png' },
  },
  {
    id: 'eg-70',
    name: 'חרפושית - מאעת ניצבת',
    categoryId: 'egyptian',
    age: 'תקופה מאוחרת',
    ageNum: -500,
    location: 'מצרים',
    material: 'אחלמה',
    materials: ['אחלמה'],
    use: 'חרפושיות',
    size: 'אורך 1.7, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית ועליה דמות האלה מאעת ניצבת ואוחזת שרביט מעוטר בצמח הפפירוס.png' },
  },
  {
    id: 'eg-71',
    name: 'חרפושית - אוסיריס לנצח',
    categoryId: 'egyptian',
    age: 'ממלכה חדשה',
    ageNum: -1300,
    location: 'מצרים',
    material: 'ישפה',
    materials: ['ישפה'],
    use: 'חרפושיות',
    size: 'אורך 2, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/חרפושית הנושאת את הכתובת _וננ-נפרו (אוסיריס) לנצח__.png' },
  },
  {
    id: 'eg-72',
    name: 'קטעי תכריכים - כתובות',
    categoryId: 'egyptian',
    age: 'סוף התקופה המאוחרת או ראשית התקופה התלמית, המאה ה-3 עד ה-2 לפני הספירה',
    ageNum: -250,
    location: 'מצרים',
    material: 'פשתן',
    materials: ['פשתן'],
    use: 'קבורה',
    size: 'אורך 32.5 ס"מ, רוחב 9.8 ס"מ',
    description: 'קטעי תכריכים של מומיה הנושאים כתובות',
    media: { type: 'image', src: 'media/artifacts/egyptian/קטע תכריכים.png' },
  },
  {
    id: 'eg-73',
    name: 'קמע - לטאה',
    categoryId: 'egyptian',
    age: 'תקופת ביניים ראשונה',
    ageNum: -2100,
    location: 'מצרים',
    material: 'סטאטיט',
    materials: ['סטאטיט'],
    use: 'פולחן',
    size: 'גובה 0.7, אורך 1.8, רוחב 1.2 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/קמע ועליו דמות לטאה.png' },
  },
  {
    id: 'eg-74',
    name: 'פסלון בדמות נפטיס',
    categoryId: 'egyptian',
    age: 'תלמית מוקדמת',
    ageNum: -300,
    location: 'מצרים',
    material: 'ברונזה',
    materials: ['ברונזה'],
    use: 'פולחן',
    size: 'גובה 11.9, רוחב 2.9 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/פסלון בדמות נפטיס.png' },
  },
  {
    id: 'eg-75',
    name: 'צלמית בדמותו של מונתו-חתפ',
    categoryId: 'egyptian',
    age: 'מאה 18 לפנה"ס',
    ageNum: -1750,
    location: 'מצרים',
    material: 'בזלת',
    materials: ['בזלת'],
    use: 'פולחן',
    size: 'גובה 26, רוחב 8.1 ס"מ',
    description: '',
    media: { type: 'image', src: 'media/artifacts/egyptian/צלמית בדמותו של מונתו-חתפ.png' },
  },
];
